language: python
python:
  - "2.7"
  - "3.4"

install:
  - python setup.py develop
  - pip install pytest pytest-cov pytest-pep8

script:
  - py.test --pep8 pinba_etl -v --cov pinba_etl --cov-report term-missing tests
